/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AviationRouteImport } from './routes/aviation'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MobilityRouteImport } from './routes/mobility'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResidencesRouteImport } from './routes/residences'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as YachtsRouteImport } from './routes/yachts'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as CustomerBookingsRouteImport } from './routes/customer.bookings'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerDocumentsRouteImport } from './routes/customer.documents'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerQuotesRouteImport } from './routes/customer.quotes'
import { Route as CustomerRequestsRouteImport } from './routes/customer.requests'
import { Route as CustomerSubscriptionRouteImport } from './routes/customer.subscription'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as SalesDashboardRouteImport } from './routes/sales.dashboard'
import { Route as SalesRequestsRouteImport } from './routes/sales.requests'
import { Route as CustomerRequestsIdRouteImport } from './routes/customer.requests.$id'
import { Route as CustomerRequestsNewRouteImport } from './routes/customer.requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AviationRoute = AviationRouteImport.update({
  id: '/aviation',
  path: '/aviation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityRoute = MobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesRoute = ResidencesRouteImport.update({
  id: '/residences',
  path: '/residences',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtsRoute = YachtsRouteImport.update({
  id: '/yachts',
  path: '/yachts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/customer/bookings',
  path: '/customer/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDocumentsRoute = CustomerDocumentsRouteImport.update({
  id: '/customer/documents',
  path: '/customer/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerQuotesRoute = CustomerQuotesRouteImport.update({
  id: '/customer/quotes',
  path: '/customer/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/customer/requests',
  path: '/customer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSubscriptionRoute = CustomerSubscriptionRouteImport.update({
  id: '/customer/subscription',
  path: '/customer/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/customer/support',
  path: '/customer/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDashboardRoute = SalesDashboardRouteImport.update({
  id: '/sales/dashboard',
  path: '/sales/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRequestsRoute = SalesRequestsRouteImport.update({
  id: '/sales/requests',
  path: '/sales/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsIdRoute = CustomerRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerRequestsRoute,
} as any)
const CustomerRequestsNewRoute = CustomerRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomerRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aviation': typeof AviationRoute
  '/concierge': typeof ConciergeRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/mobility': typeof MobilityRoute
  '/private': typeof PrivateRoute
  '/register': typeof RegisterRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residences': typeof ResidencesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/yachts': typeof YachtsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/documents': typeof CustomerDocumentsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/customer/subscription': typeof CustomerSubscriptionRoute
  '/customer/support': typeof CustomerSupportRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/requests': typeof SalesRequestsRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
  '/customer/requests/new': typeof CustomerRequestsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aviation': typeof AviationRoute
  '/concierge': typeof ConciergeRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/mobility': typeof MobilityRoute
  '/private': typeof PrivateRoute
  '/register': typeof RegisterRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residences': typeof ResidencesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/yachts': typeof YachtsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/documents': typeof CustomerDocumentsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/customer/subscription': typeof CustomerSubscriptionRoute
  '/customer/support': typeof CustomerSupportRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/requests': typeof SalesRequestsRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
  '/customer/requests/new': typeof CustomerRequestsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aviation': typeof AviationRoute
  '/concierge': typeof ConciergeRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/mobility': typeof MobilityRoute
  '/private': typeof PrivateRoute
  '/register': typeof RegisterRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residences': typeof ResidencesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/yachts': typeof YachtsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/documents': typeof CustomerDocumentsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/customer/subscription': typeof CustomerSubscriptionRoute
  '/customer/support': typeof CustomerSupportRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/requests': typeof SalesRequestsRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
  '/customer/requests/new': typeof CustomerRequestsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aviation'
    | '/concierge'
    | '/destinations'
    | '/experiences'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/mobility'
    | '/private'
    | '/register'
    | '/request-access'
    | '/reset-password'
    | '/residences'
    | '/subscriptions'
    | '/yachts'
    | '/admin/dashboard'
    | '/admin/requests'
    | '/customer/bookings'
    | '/customer/dashboard'
    | '/customer/documents'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/quotes'
    | '/customer/requests'
    | '/customer/subscription'
    | '/customer/support'
    | '/sales/dashboard'
    | '/sales/requests'
    | '/customer/requests/$id'
    | '/customer/requests/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aviation'
    | '/concierge'
    | '/destinations'
    | '/experiences'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/mobility'
    | '/private'
    | '/register'
    | '/request-access'
    | '/reset-password'
    | '/residences'
    | '/subscriptions'
    | '/yachts'
    | '/admin/dashboard'
    | '/admin/requests'
    | '/customer/bookings'
    | '/customer/dashboard'
    | '/customer/documents'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/quotes'
    | '/customer/requests'
    | '/customer/subscription'
    | '/customer/support'
    | '/sales/dashboard'
    | '/sales/requests'
    | '/customer/requests/$id'
    | '/customer/requests/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aviation'
    | '/concierge'
    | '/destinations'
    | '/experiences'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/mobility'
    | '/private'
    | '/register'
    | '/request-access'
    | '/reset-password'
    | '/residences'
    | '/subscriptions'
    | '/yachts'
    | '/admin/dashboard'
    | '/admin/requests'
    | '/customer/bookings'
    | '/customer/dashboard'
    | '/customer/documents'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/quotes'
    | '/customer/requests'
    | '/customer/subscription'
    | '/customer/support'
    | '/sales/dashboard'
    | '/sales/requests'
    | '/customer/requests/$id'
    | '/customer/requests/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AviationRoute: typeof AviationRoute
  ConciergeRoute: typeof ConciergeRoute
  DestinationsRoute: typeof DestinationsRoute
  ExperiencesRoute: typeof ExperiencesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  MobilityRoute: typeof MobilityRoute
  PrivateRoute: typeof PrivateRoute
  RegisterRoute: typeof RegisterRoute
  RequestAccessRoute: typeof RequestAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResidencesRoute: typeof ResidencesRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  YachtsRoute: typeof YachtsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerDocumentsRoute: typeof CustomerDocumentsRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerQuotesRoute: typeof CustomerQuotesRoute
  CustomerRequestsRoute: typeof CustomerRequestsRouteWithChildren
  CustomerSubscriptionRoute: typeof CustomerSubscriptionRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  SalesDashboardRoute: typeof SalesDashboardRoute
  SalesRequestsRoute: typeof SalesRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviation': {
      id: '/aviation'
      path: '/aviation'
      fullPath: '/aviation'
      preLoaderRoute: typeof AviationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility': {
      id: '/mobility'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences': {
      id: '/residences'
      path: '/residences'
      fullPath: '/residences'
      preLoaderRoute: typeof ResidencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yachts': {
      id: '/yachts'
      path: '/yachts'
      fullPath: '/yachts'
      preLoaderRoute: typeof YachtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/customer/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/documents': {
      id: '/customer/documents'
      path: '/customer/documents'
      fullPath: '/customer/documents'
      preLoaderRoute: typeof CustomerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/quotes': {
      id: '/customer/quotes'
      path: '/customer/quotes'
      fullPath: '/customer/quotes'
      preLoaderRoute: typeof CustomerQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests': {
      id: '/customer/requests'
      path: '/customer/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/subscription': {
      id: '/customer/subscription'
      path: '/customer/subscription'
      fullPath: '/customer/subscription'
      preLoaderRoute: typeof CustomerSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/customer/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/dashboard': {
      id: '/sales/dashboard'
      path: '/sales/dashboard'
      fullPath: '/sales/dashboard'
      preLoaderRoute: typeof SalesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/requests': {
      id: '/sales/requests'
      path: '/sales/requests'
      fullPath: '/sales/requests'
      preLoaderRoute: typeof SalesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests/$id': {
      id: '/customer/requests/$id'
      path: '/$id'
      fullPath: '/customer/requests/$id'
      preLoaderRoute: typeof CustomerRequestsIdRouteImport
      parentRoute: typeof CustomerRequestsRoute
    }
    '/customer/requests/new': {
      id: '/customer/requests/new'
      path: '/new'
      fullPath: '/customer/requests/new'
      preLoaderRoute: typeof CustomerRequestsNewRouteImport
      parentRoute: typeof CustomerRequestsRoute
    }
  }
}

interface CustomerRequestsRouteChildren {
  CustomerRequestsIdRoute: typeof CustomerRequestsIdRoute
  CustomerRequestsNewRoute: typeof CustomerRequestsNewRoute
}

const CustomerRequestsRouteChildren: CustomerRequestsRouteChildren = {
  CustomerRequestsIdRoute: CustomerRequestsIdRoute,
  CustomerRequestsNewRoute: CustomerRequestsNewRoute,
}

const CustomerRequestsRouteWithChildren =
  CustomerRequestsRoute._addFileChildren(CustomerRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AviationRoute: AviationRoute,
  ConciergeRoute: ConciergeRoute,
  DestinationsRoute: DestinationsRoute,
  ExperiencesRoute: ExperiencesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  MobilityRoute: MobilityRoute,
  PrivateRoute: PrivateRoute,
  RegisterRoute: RegisterRoute,
  RequestAccessRoute: RequestAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResidencesRoute: ResidencesRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  YachtsRoute: YachtsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerDocumentsRoute: CustomerDocumentsRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerQuotesRoute: CustomerQuotesRoute,
  CustomerRequestsRoute: CustomerRequestsRouteWithChildren,
  CustomerSubscriptionRoute: CustomerSubscriptionRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  SalesDashboardRoute: SalesDashboardRoute,
  SalesRequestsRoute: SalesRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
